import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Providers } from "@/components/Providers";



export const metadata: Metadata = {
  title: "Clothing Lab",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
  <body className="min-h-screen flex flex-col w-full">
    <Providers>
      <Navbar />
      {children}
    </Providers>
  </body>
</html>
  );
}

